spring:
  application:
    name=spring-boot-course
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    #Set logging pattern for console and in file
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    #log file path and name configuration
  file:
    name: ./log/application.log
    #log file rolling configuration
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 5KB
      file-name-pattern: ./log/application-%d{yyyy-MM-dd}.%i.log
      #The maximum amount of size log archives can take before being deleted.
      #total-size-cap: 10KB
  #Set logging level
  level:
    root: INFO
    com.vednexgen: DEBUG